###
### appveyor.yml
###

platform:
  - x64
environment:
  matrix:
    - nodejs_version: '10'
    #- nodejs_version: '9'
    #- nodejs_version: '8'
    #- nodejs_version: '6'
install:
  - set CI=true
  #- set PATH=%PROGRAMFILES(X86)%\Growl for Windows;%PATH%
  ## Manual Growl install
  - ps: echo "*** download"
  - ps: $exePath = "$($env:USERPROFILE)\GrowlInstaller.exe"
  - ps: (New-Object Net.WebClient).DownloadFile('http://www.growlforwindows.com/gfw/downloads/GrowlInstaller.exe', $exePath)
  - ps: echo "*** dearchive"
  - ps: mkdir C:\GrowlInstaller
  - ps: 7z x $exePath -oC:\GrowlInstaller | out-null
  - ps: echo "*** install"
  - ps: cmd /c start /wait msiexec /i C:\GrowlInstaller\Growl_v2.0.msi /quiet
  - ps: $env:path = "C:\Program Files (x86)\Growl for Windows;$env:path"
  - ps: Add-AppveyorMessage "Growl installed"
  - ps: Add-AppveyorMessage "Starting Growl service..."
  - ps: Start-Process -NoNewWindow Growl
  - ps: echo "*** root"
  - ps: dir "C:\"
  - ps: echo "*** home"
  - ps: dir "\Users\appveyor"
  - ps: echo "*** GrowlInstaller"
  - ps: dir "C:\GrowlInstaller"
  - ps: echo "*** Program Files (x86)"
  - ps: dir "C:\Program Files (x86)"
  - ps: echo "*** Growl for Windows"
  - ps: dir "C:\Program Files (x86)\Growl for Windows"
  - set PATH=%APPDATA%\npm;C:\MinGW\bin;%PATH%
  - set
  - ps: echo "###################################"
  - ps: Install-Product node $env:nodejs_version x64
  - npm install -g npm@^5
  - npm ci --ignore-scripts
matrix:
  fast_finish: true
build: off
version: '{build}'
shallow_clone: true
clone_depth: 1
before_test:
  #- ps: Start-Sleep -Seconds 1
  - ps: growlnotify test
test_script:
  - node --version
  - npm --version
  - npm start test.node
skip_commits:
  message: /\[ci\s+skip\]/

