###
### appveyor.yml
###

platform:
  - x64
environment:
  matrix:
    - nodejs_version: '10'
    #- nodejs_version: '9'
    #- nodejs_version: '8'
    #- nodejs_version: '6'
install:
  - set CI=true
  #- set PATH=%PROGRAMFILES(X86)%\Growl for Windows;%PATH%
  - set PATH=%APPDATA%\npm;C:\MinGW\bin;%PATH%
  - set
  ## Manual Growl install
  - ps: $exePath = "$($env:USERPROFILE)\GrowlInstaller.exe"
  - ps: (New-Object Net.WebClient).DownloadFile('http://www.growlforwindows.com/gfw/downloads/GrowlInstaller.exe', $exePath)
  - ps: mkdir C:\GrowlInstaller
  - ps: 7z x $exePath -oC:\GrowlInstaller | out-null
  - ps: cmd /c start /wait msiexec /i C:\GrowlInstaller\Growl_v2.0.msi /quiet
  - ps: $env:path = "C:\Program Files (x86)\Growl for Windows;$env:path"
  - ps: Add-AppveyorMessage "Growl installed"
  - ps: Start-Process -NoNewWindow Growl
  #- ps: $exeFile = "GrowlInstaller.exe"
  #- ps: $exeDir  = "$($env:USERPROFILE)\Downloads"
  #- ps: $exePath = "$exeDir\$exeFile"
  #- ps: $exeURL = "http://www.growlforwindows.com/gfw/downloads/$exeFile"
  #- ps: echo "*** download"
  #- ps: (New-Object Net.WebClient).DownloadFile($exeURL, $exePath)
  #- ps: $?
  #- ps: $instFile = "Growl_v2.0.msi"
  #- ps: $instDir = "C:\GrowlInstaller"
  #- ps: $instPath = "$instDir/$instFile"
  #- ps: mkdir $instPath
  #- ps: echo "*** dearchive"
  #- ps: 7z x $exePath -o$instDir | out-null
  #- ps: 7z x $exePath -o$instDir | out-null
  #- ps: $?
  #- ps: echo "*** GrowlInstaller"
  #- ps: dir "C:\GrowlInstaller"
  #- ps: echo "*** Run installer"
  #- ps: cmd /c start /wait msiexec /i "$instPath" /quiet
  #- ps: cmd /c start /wait msiexec /i "C:\GrowlInstaller\Growl_v2.0.msi" /quiet
  #- ps: $?
  #- ps: rm $exePath
  #- ps: rmdir -r $instPath
  - ps: echo "*** root"
  - ps: dir "C:\"
  - ps: echo "*** home"
  - ps: dir "\Users\appveyor"
  - ps: echo "*** GrowlInstaller"
  - ps: dir "C:\GrowlInstaller"
  - ps: echo "*** Program Files"
  - ps: dir "C:\Program Files"
  - ps: echo "*** Program Files (x86)"
  - ps: dir "C:\Program Files (x86)"
  - ps: echo "*** Growl for Windows"
  - ps: dir "C:\Program Files (x86)\Growl for Windows"
  - ps: echo "###################################"
  - ps: Install-Product node $env:nodejs_version x64
  - npm install -g npm@^5
  - npm ci --ignore-scripts
  ## Chocolatey Growl install fails -- out of date package metadata
  #- cinst growl
matrix:
  fast_finish: true
after_install:
  - ps: Add-AppveyorMessage "after_install exists?"
  - ps: Start-Process -NoNewWindow Growl
  - ps: growlnotify test
before_build:
  - ps: Add-AppveyorMessage "before_build run if build turned off?"
  - ps: Start-Process -NoNewWindow Growl
  - ps: growlnotify test
build: off
version: '{build}'
shallow_clone: true
clone_depth: 1
before_test:
  - ps: Add-AppveyorMessage "Before testing"


test_script:
  - node --version
  - npm --version
  - npm start test.node
skip_commits:
  message: /\[ci\s+skip\]/

