###
### appveyor.yml
###

platform:
  - x64
environment:
  matrix:
    - nodejs_version: '10'
    - nodejs_version: '9'
    - nodejs_version: '8'
    - nodejs_version: '6'
install:
  - ps: Install-Product node $env:nodejs_version x64
  - set CI=true
  - set PATH=%PROGRAMFILES(X86)%\Growl for Windows;%PATH%
  - set PATH=%APPDATA%\npm;C:\MinGW\bin;%PATH%
  - set
  - npm install -g npm@^5
  - npm ci --ignore-scripts
  ## Chocolatey Growl install fails -- out of date package metadata
  #- cinst growl
  ## Manual Growl install
  - ps: $exeFile = "GrowlInstaller.exe"
  - ps: $exePath = "$($env:USERPROFILE)\Downloads\$exeFile"
  - ps: $exeURL = "http://www.growlforwindows.com/gfw/downloads/$exeFile"
  - ps: (New-Object Net.WebClient).DownloadFile($exeURL, $exePath)
  - ps: $instPath = "C:\GrowlInstaller"
  - ps: $instMSI = "Growl_v2.0.msi"
  - ps: mkdir $instPath
  - ps: 7z x $exePath -o$instPath | out-null
  - ps: rm $exePath
  - ps: cmd /c start /wait msiexec /i $instPath\$instMSI /quiet
  - ps: rmdir -r $instPath
matrix:
  fast_finish: true
build: off
version: '{build}'
shallow_clone: true
clone_depth: 1
test_script:
  - node --version
  - npm --version
  - npm start test.node
skip_commits:
  message: /\[ci\s+skip\]/

