###
### appveyor.yml
###

## General configuration
version: '{build}'
skip_commits:
  message: /\[ci\s+skip\]/

## Environment configuration
shallow_clone: true
clone_depth: 1
environment:
  matrix:
    - nodejs_version: '10'
    #- nodejs_version: '9'
    #- nodejs_version: '8'
    #- nodejs_version: '6'
matrix:
  fast_finish: true
install:
  ## Manual Growl install
  - ps: Add-AppveyorMessage "Installing Growl..."
  - ps: $exePath = "$($env:USERPROFILE)\GrowlInstaller.exe"
  - ps: (New-Object Net.WebClient).DownloadFile('http://www.growlforwindows.com/gfw/downloads/GrowlInstaller.exe', $exePath)
  - ps: mkdir C:\GrowlInstaller | out-null
  - ps: 7z x $exePath -oC:\GrowlInstaller | out-null
  - ps: cmd /c start /wait msiexec /i C:\GrowlInstaller\Growl_v2.0.msi /quiet
  - ps: $env:path = "C:\Program Files (x86)\Growl for Windows;$env:path"
  ## Node-related installs
  - ps: Add-AppveyorMessage "Installing Node..."
  - set PATH=%APPDATA%\npm;C:\MinGW\bin;%PATH%
  - ps: Install-Product node $env:nodejs_version x64
  - ps: Add-AppveyorMessage "Installing npm..."
  - npm install -g npm@^5
  ## Mocha-related package installs
  - ps: Add-AppveyorMessage "Installing Mocha dependencies..."
  - npm ci --ignore-scripts

## Build configuration
platform:
  - x64
before_build:
  - ps: Add-AppveyorMessage "Starting Growl service..."
  - ps: Start-Process -NoNewWindow Growl
  - ps: Start-Sleep -Seconds 1
build_script:
  - ps: Add-AppveyorMessage "Verify Growl works..."
  - ps: growlnotify test

## Test configuration
before_test:
  - set CI=true
test_script:
  - ps: Add-AppveyorMessage "Checking versions..."
  - node --version
  - npm --version
  - ps: Add-AppveyorMessage "Running tests..."
  - npm start test.node
  - ps: Add-AppveyorMessage "Done"

