###
### appveyor.yml
###

platform:
  - x64
environment:
  matrix:
    - nodejs_version: '10'
    #- nodejs_version: '9'
    #- nodejs_version: '8'
    #- nodejs_version: '6'
install:
  - set CI=true
  - set PATH=%PROGRAMFILES(X86)%\Growl for Windows;%PATH%
  - set PATH=%APPDATA%\npm;C:\MinGW\bin;%PATH%
  - set
  ## Manual Growl install
  - ps: $exeFile = "GrowlInstaller.exe"
  - ps: $exePath = "$($env:USERPROFILE)\Downloads\$exeFile"
  - ps: $exeURL = "http://www.growlforwindows.com/gfw/downloads/$exeFile"
  - ps: echo "*** download"
  - ps: (New-Object Net.WebClient).DownloadFile($exeURL, $exePath)
  - ps: $?
  - ps: $instPath = "C:\GrowlInstaller"
  - ps: $instMSI = "Growl_v2.0.msi"
  - ps: mkdir $instPath
  - ps: echo "*** dearchive"
  #- ps: 7z x $exePath -o$instPath | out-null
  - ps: 7z x $exePath -o$instPath | out-null
  - ps: $?
  - ps: echo "*** GrowlInstaller"
  - ps: dir "C:\GrowlInstaller"
  - ps: echo "*** Run installer"
  #- ps: cmd /c start /wait msiexec /i "$instPath\$instMSI" /quiet
  - ps: cmd /c start /wait msiexec /i "C:\GrowlInstaller\Growl_v2.0.msi" /quiet
  - ps: $?
  #- ps: rm $exePath
  #- ps: rmdir -r $instPath
  - ps: echo "*** root"
  - ps: dir "C:\"
  - ps: echo "*** GrowlInstaller"
  - ps: dir "C:\GrowlInstaller"
  - ps: echo "*** Program Files"
  - ps: dir "C:\Program Files"
  - ps: echo "*** Program Files (x86)"
  - ps: dir "C:\Program Files (x86)"
  - ps: echo "*** Growl for Windows"
  - ps: dir "C:\Program Files (x86)\Growl for Windows"
  - ps: growlnotify test
  - ps: echo "###################################"
  - ps: Install-Product node $env:nodejs_version x64
  - npm install -g npm@^5
  - npm ci --ignore-scripts
  ## Chocolatey Growl install fails -- out of date package metadata
  #- cinst growl
matrix:
  fast_finish: true
build: off
version: '{build}'
shallow_clone: true
clone_depth: 1
test_script:
  - node --version
  - npm --version
  - npm start test.node
skip_commits:
  message: /\[ci\s+skip\]/

